---
- name: Example of Array listing variables
  hosts: test
  gather_facts: false
  become: true
  vars:
    mypkgs:
      - ftp
      - vsftpd
      - zsh
      - telnet
      - httpd
  tasks:
    - name: Installing the Package "{{ mypkgs [4] }}" 
      yum: 
        name: "{{ mypkgs [4] }}"
        state: latest
...
