---
- hosts: all
  tasks:
    - file:
          path: /tmp/testdir
          state: directory

    - copy:
          src: /etc/fstab
          dest: /tmp/testdir

    - yum:
         name:
           - httpd
           - wget
 
    - service:
            name: httpd
            state: started
            enabled: true
               
